if [ catch {
    set i 0
    while { $i <= 14 } {
	if { $i < 10 } {
	    set filled 0$i
	} else {
	    set filled $i
	}

	set root testdata/diff/$filled
	set a $root
	append a a.xml
	set b $root
	append b b.xml
	set d $root
	append d d.xml
	set res $filled
	append res res.xml

	exec cmd/dm $a $b > $res
	exec diff $res $d
	exec rm $res
	pass $filled

	incr i
    }

    pass "diff" } err ] {
    puts stderr "ERROR: $err"
    fail "diff"
}
