if [ catch {
    set i 0
    while { $i <= 1 } {
	if { $i < 10 } {
	    set filled 0$i
	} else {
	    set filled $i
	}

	set root testdata/faildiff/$filled
	set a $root
	append a a.xml
	set b $root
	append b b.xml
	set e $root
	append e .err
	set res $filled
	append res res.err

	if [ catch {
	    exec cmd/dm $a $b >& $res
	    fail $filled } err ] {
	    exec diff $res $e
	    exec rm $res
	    pass $filled
	}

	incr i
    }

    pass "faildiff" } err ] {
    puts stderr "ERROR: $err"
    fail "faildiff"
}

